// Accurate Earth — CPU texture-mapped sphere, browser-independent
(()=>{
 const canvas=document.getElementById('earthGL'),overlay=document.getElementById('earthNet'),ctx=canvas.getContext('2d',{alpha:true}),ox=overlay.getContext('2d');if(!ctx||!ox)return;let W=1,H=1,D=1,raf=0,last=0,visible=true,start=performance.now(),yaw=1.92,pitch=.17,targetYaw=yaw,targetPitch=pitch,srcData=null,srcW=0,srcH=0,mapCanvas=document.createElement('canvas'),mapCtx=mapCanvas.getContext('2d'),sphere=document.createElement('canvas'),sctx=sphere.getContext('2d'),S=420,geo=null;
 const hubs=[[25.76,-80.19],[40.71,-74.01],[37.77,-122.42],[51.51,-.13],[25.20,55.27],[1.35,103.82],[35.68,139.65],[-33.87,151.21],[-23.55,-46.63],[-26.20,28.05]],links=[[0,1],[0,2],[1,3],[3,4],[4,5],[5,6],[6,7],[0,8],[3,9],[9,4]],TAU=Math.PI*2;
 const light=(()=>{let v=[-.45,.65,1],m=Math.hypot(...v);return v.map(n=>n/m)})();
 const img=new Image();img.onload=()=>{mapCanvas.width=img.naturalWidth;mapCanvas.height=img.naturalHeight;mapCtx.drawImage(img,0,0);srcW=mapCanvas.width;srcH=mapCanvas.height;srcData=mapCtx.getImageData(0,0,srcW,srcH).data;prepareSphere();draw(performance.now())};img.src=EARTH_TEXTURE;
 function prepareSphere(){S=innerWidth<650?300:innerWidth<1100?380:480;sphere.width=sphere.height=S;const N=S*S;geo={nx:new Float32Array(N),ny:new Float32Array(N),nz:new Float32Array(N),inside:new Uint8Array(N),shade:new Float32Array(N),fres:new Float32Array(N)};const R=S*.475,c=S/2;for(let y=0;y<S;y++)for(let x=0;x<S;x++){const i=y*S+x,sx=(x+.5-c)/R,sy=(y+.5-c)/R,r2=sx*sx+sy*sy;if(r2>1)continue;const nx=sx,ny=-sy,nz=Math.sqrt(Math.max(0,1-r2));geo.inside[i]=1;geo.nx[i]=nx;geo.ny[i]=ny;geo.nz[i]=nz;geo.shade[i]=.34+.66*Math.max(0,nx*light[0]+ny*light[1]+nz*light[2]);geo.fres[i]=Math.pow(1-nz,2.15)}}
 function resize(){const r=canvas.getBoundingClientRect();D=Math.min(devicePixelRatio||1,2);W=Math.max(1,r.width);H=Math.max(1,r.height);canvas.width=overlay.width=Math.round(W*D);canvas.height=overlay.height=Math.round(H*D);ctx.setTransform(D,0,0,D,0,0);ox.setTransform(D,0,0,D,0,0);const desired=innerWidth<650?300:innerWidth<1100?380:480;if(desired!==S&&srcData)prepareSphere()}
 function sample(u,v){let x=((u%1+1)%1)*(srcW-1),y=Math.max(0,Math.min(1,v))*(srcH-1),ix=x|0,iy=y|0,j=(iy*srcW+ix)*4;return[srcData[j],srcData[j+1],srcData[j+2]]}
 function renderSphere(){if(!srcData||!geo)return;const out=sctx.createImageData(S,S),dst=out.data,cy=Math.cos(yaw),sy=Math.sin(yaw),cp=Math.cos(pitch),sp=Math.sin(pitch);for(let i=0;i<S*S;i++){if(!geo.inside[i])continue;let x=geo.nx[i],y=geo.ny[i],z=geo.nz[i];let y1=cp*y+sp*z,z1=-sp*y+cp*z;let xw=cy*x+sy*z1,zw=-sy*x+cy*z1,yw=y1;let lon=Math.atan2(zw,xw),lat=Math.asin(Math.max(-1,Math.min(1,yw))),u=lon/TAU+.5,v=.5-lat/Math.PI,rgb=sample(u,v),sh=geo.shade[i],coast=Math.max(0,Math.min(1,(rgb[0]-55)/150)),fr=geo.fres[i],j=i*4;dst[j]=Math.min(255,rgb[0]*sh*1.12+255*coast*.21+255*fr*.10);dst[j+1]=Math.min(255,rgb[1]*sh*1.08+108*coast*.18+110*fr*.085);dst[j+2]=Math.min(255,rgb[2]*sh*1.05+14*coast*.08+20*fr*.045);dst[j+3]=255}sctx.putImageData(out,0,0)}
 function v3(lat,lo){const p=lat*Math.PI/180,l=lo*Math.PI/180,c=Math.cos(p);return[c*Math.cos(l),Math.sin(p),c*Math.sin(l)]}function rot(v){let [xx,yy,zz]=v,cy=Math.cos(yaw),sy=Math.sin(yaw),x1=cy*xx-sy*zz,z1=sy*xx+cy*zz,cp=Math.cos(pitch),sp=Math.sin(pitch),y1=cp*yy-sp*z1,z2=sp*yy+cp*z1;return[x1,y1,z2]}function proj(v){const r=rot(v),R=Math.min(W,H)*.405;return{x:W*.5+r[0]*R,y:H*.5-r[1]*R,z:r[2]}}function slerp(a,b,t){let va=v3(a[0],a[1]),vb=v3(b[0],b[1]),dot=Math.max(-1,Math.min(1,va[0]*vb[0]+va[1]*vb[1]+va[2]*vb[2])),om=Math.acos(dot),so=Math.sin(om);if(so<1e-5)return va;let A=Math.sin((1-t)*om)/so,B=Math.sin(t*om)/so;return[va[0]*A+vb[0]*B,va[1]*A+vb[1]*B,va[2]*A+vb[2]*B]}
 function drawNetwork(t){ox.clearRect(0,0,W,H);ox.save();ox.globalCompositeOperation='lighter';links.forEach((L,i)=>{const a=hubs[L[0]],b=hubs[L[1]];ox.beginPath();let started=false;for(let k=0;k<=72;k++){const q=slerp(a,b,k/72),p=proj(q);if(p.z>0){started?ox.lineTo(p.x,p.y):ox.moveTo(p.x,p.y);started=true}else started=false}ox.strokeStyle='rgba(255,168,44,.18)';ox.lineWidth=.8;ox.stroke();const tt=reduce?.45:((t-start)*.000042+i*.119)%1,q=slerp(a,b,tt),p=proj(q);if(p.z>0){ox.beginPath();ox.arc(p.x,p.y,2.15,0,TAU);ox.fillStyle='rgba(255,196,108,.98)';ox.shadowColor='#ff8a00';ox.shadowBlur=13;ox.fill();ox.shadowBlur=0}});hubs.forEach(h=>{const p=proj(v3(h[0],h[1]));if(p.z>0){ox.beginPath();ox.arc(p.x,p.y,2.05,0,TAU);ox.fillStyle='rgba(255,144,12,.94)';ox.shadowColor='#ff8a00';ox.shadowBlur=11;ox.fill();ox.shadowBlur=0}});ox.restore()}
 function draw(t){yaw+=((targetYaw-yaw)*.035)+(reduce?0:.00038);pitch+=(targetPitch-pitch)*.035;renderSphere();ctx.clearRect(0,0,W,H);const R=Math.min(W,H)*.405,cx=W*.5,cy=H*.5,g=ctx.createRadialGradient(cx,cy,R*.74,cx,cy,R*1.18);g.addColorStop(0,'rgba(255,125,0,0)');g.addColorStop(.73,'rgba(255,125,0,.035)');g.addColorStop(1,'rgba(255,125,0,0)');ctx.fillStyle=g;ctx.fillRect(0,0,W,H);ctx.save();ctx.shadowColor='rgba(255,138,0,.22)';ctx.shadowBlur=32;ctx.globalAlpha=.97;ctx.drawImage(sphere,cx-R,cy-R,R*2,R*2);ctx.restore();ctx.beginPath();ctx.arc(cx,cy,R,0,TAU);ctx.strokeStyle='rgba(255,164,44,.21)';ctx.lineWidth=.8;ctx.stroke();drawNetwork(t)}
 function loop(t){if(t-last>(innerWidth<650?60:45)){last=t;draw(t)}if(!reduce&&visible&&!document.hidden)raf=requestAnimationFrame(loop);else raf=0}resize();new ResizeObserver(resize).observe(canvas);new IntersectionObserver(e=>{visible=!!e[0]?.isIntersecting;if(visible&&!raf&&!reduce)raf=requestAnimationFrame(loop)},{rootMargin:'180px'}).observe(canvas);const wrap=canvas.parentElement;if(matchMedia('(pointer:fine)').matches)wrap.addEventListener('pointermove',e=>{const r=wrap.getBoundingClientRect();targetYaw=1.92+((e.clientX-r.left)/r.width-.5)*.34;targetPitch=.17+((e.clientY-r.top)/r.height-.5)*-.20},{passive:true});if(!reduce)raf=requestAnimationFrame(loop)
})();
