const EARTH_TEXTURE='data:image/webp;base64,'+(window.__ST8_EARTH_B64||'');
;
const reduce=matchMedia('(prefers-reduced-motion: reduce)').matches;
const nav=document.getElementById('nav');addEventListener('scroll',()=>nav.classList.toggle('scrolled',scrollY>20),{passive:true});
const menuBtn=document.getElementById('menuBtn'),mobileMenu=document.getElementById('mobileMenu');function setMenu(open){mobileMenu.classList.toggle('open',open);menuBtn.textContent=open?'CLOSE':'MENU';menuBtn.setAttribute('aria-expanded',String(open));mobileMenu.setAttribute('aria-hidden',String(!open))}menuBtn.addEventListener('click',()=>setMenu(!mobileMenu.classList.contains('open')));mobileMenu.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>setMenu(false)));addEventListener('keydown',e=>{if(e.key==='Escape')setMenu(false)});
const glow=document.getElementById('cursorGlow');if(matchMedia('(pointer:fine)').matches)addEventListener('pointermove',e=>{glow.style.transform=`translate(${e.clientX-270}px,${e.clientY-270}px)`},{passive:true});
const io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('on');io.unobserve(e.target)}}),{threshold:.12,rootMargin:'0px 0px -5% 0px'});document.querySelectorAll('.reveal').forEach(el=>io.observe(el));

// HERO — semantic agent-state simulation. No static graph: only living roles + transient signed activity.
(()=>{
 const c=document.getElementById('heroFlow'),ctx=c&&c.getContext('2d',{alpha:true});if(!c||!ctx)return;
 let w=1,h=1,dpr=1,raf=0,last=0,visible=true,start=performance.now(),mouseX=0,mouseY=0;const FPS=36,TAU=Math.PI*2;
 const role={
  human:{rgb:[255,235,202],shape:'human',center:[-185,-105,65],count:10,spread:[68,58,90]},
  agent:{rgb:[255,126,0],shape:'agent',center:[-190,120,-55],count:14,spread:[78,68,105]},
  compute:{rgb:[255,184,66],shape:'compute',center:[132,112,-70],count:8,spread:[55,48,75]},
  proof:{rgb:[255,244,222],shape:'proof',center:[154,-100,95],count:7,spread:[50,44,62]}
 };
 const sprites={};function makeSprite(rgb){const k=rgb.join(',');if(sprites[k])return sprites[k];const s=document.createElement('canvas');s.width=s.height=96;const g=s.getContext('2d'),r=g.createRadialGradient(48,48,0,48,48,46);r.addColorStop(0,`rgba(${k},1)`);r.addColorStop(.10,`rgba(${k},.92)`);r.addColorStop(.34,`rgba(${k},.22)`);r.addColorStop(1,`rgba(${k},0)`);g.fillStyle=r;g.fillRect(0,0,96,96);return sprites[k]=s}
 Object.values(role).forEach(r=>makeSprite(r.rgb));
 function seed(n){const x=Math.sin(n*127.1+311.7)*43758.5453;return x-Math.floor(x)}
 const nodes={};Object.entries(role).forEach(([name,r],ri)=>{nodes[name]=Array.from({length:r.count},(_,i)=>({role:name,id:i,a:seed(i+ri*43)*TAU,b:seed(i*9+ri*17)*TAU,p:seed(i*23+ri*7)*TAU,s:.75+seed(i*31+ri)*.45,spin:(.00012+seed(i*5+ri)*.00011)*(i%2?1:-1)}))});
 const out={role:'out',id:0};
 const events=Array.from({length:12},(_,i)=>({source:i%3===0?'human':'agent',si:i%(i%3===0?role.human.count:role.agent.count),compute:i%2===0,ci:i%role.compute.count,pi:(i*3)%role.proof.count,offset:i*615}));
 const dust=Array.from({length:70},(_,i)=>({a:seed(i)*TAU,r:115+seed(i+12)*260,z:-160+seed(i+44)*320,y:(seed(i+27)-.5)*130,p:seed(i+72)*TAU}));
 function resize(){const r=c.getBoundingClientRect();dpr=Math.min(devicePixelRatio||1,1.8);w=Math.max(1,r.width);h=Math.max(1,r.height);c.width=Math.round(w*dpr);c.height=Math.round(h*dpr);ctx.setTransform(dpr,0,0,dpr,0,0)}
 function nodeWorld(n,time){const d=role[n.role],sp=d.spread,t=n.a+time*n.spin;return[d.center[0]+Math.cos(t)*sp[0]*(.55+.45*Math.sin(n.b+time*.00017)),d.center[1]+Math.sin(t*.86+n.b)*sp[1],d.center[2]+Math.sin(t+n.p)*sp[2]]}
 function rotate(v,time){const yaw=time*.000055+mouseX*.16,pitch=.13+mouseY*.10,cy=Math.cos(yaw),sy=Math.sin(yaw),cp=Math.cos(pitch),sp=Math.sin(pitch),x=cy*v[0]+sy*v[2],z=-sy*v[0]+cy*v[2],y=cp*v[1]-sp*z,z2=sp*v[1]+cp*z;return[x,y,z2]}
 function project(v,time){const compact=w<700?.60:w<1000?.82:1,rv=rotate([v[0]*compact,v[1]*compact,v[2]*compact],time),cx=w*(w<700?.50:w<1000?.67:.775),cy=h*(w<700?.50:.50),f=w<700?650:900,den=f-rv[2],s=f/den;return{x:cx+rv[0]*s,y:cy+rv[1]*s,z:rv[2],s}}
 function rgba(rgb,a){return`rgba(${rgb[0]},${rgb[1]},${rgb[2]},${a})`}
 function glow(x,y,size,rgb,a){const im=makeSprite(rgb),d=size*20;ctx.globalAlpha=a;ctx.drawImage(im,x-d/2,y-d/2,d,d);ctx.globalAlpha=1}
 function drawNode(p,name,alpha){const d=role[name],rgb=d.rgb,sz=(name==='proof'?5.6:name==='compute'?5.0:name==='human'?4.8:4.7)*Math.max(.75,p.s);ctx.save();ctx.translate(p.x,p.y);ctx.globalAlpha=alpha;ctx.lineWidth=.8;ctx.strokeStyle=rgba(rgb,.92);ctx.fillStyle=rgba(rgb,.90);if(d.shape==='human'){ctx.beginPath();ctx.arc(0,0,sz*.55,0,TAU);ctx.stroke();ctx.beginPath();ctx.arc(0,0,sz*.18,0,TAU);ctx.fill()}else if(d.shape==='agent'){ctx.beginPath();ctx.moveTo(0,-sz*.65);ctx.lineTo(sz*.62,sz*.48);ctx.lineTo(-sz*.62,sz*.48);ctx.closePath();ctx.stroke();ctx.beginPath();ctx.arc(0,sz*.05,sz*.14,0,TAU);ctx.fill()}else if(d.shape==='compute'){ctx.strokeRect(-sz*.52,-sz*.52,sz*1.04,sz*1.04);ctx.beginPath();ctx.moveTo(-sz*.30,0);ctx.lineTo(sz*.30,0);ctx.moveTo(0,-sz*.30);ctx.lineTo(0,sz*.30);ctx.stroke()}else{ctx.beginPath();ctx.arc(0,0,sz*.78,0,TAU);ctx.stroke();ctx.beginPath();ctx.arc(0,0,sz*.38,0,TAU);ctx.stroke()}ctx.restore();glow(p.x,p.y,name==='proof'?1.0:.66,rgb,alpha*.5)}
 function bez(a,b,bias=0){const dx=b.x-a.x,dy=b.y-a.y,L=Math.hypot(dx,dy)||1,nx=-dy/L,ny=dx/L,bend=Math.min(80,L*.18)*(bias>=0?1:-1);return{x1:a.x+dx*.33+nx*bend*.62,y1:a.y+dy*.33+ny*bend*.62,x2:a.x+dx*.67+nx*bend,y2:a.y+dy*.67+ny*bend}}
 function cubic(a,c,b,t){const u=1-t;return{x:u*u*u*a.x+3*u*u*t*c.x1+3*u*t*t*c.x2+t*t*t*b.x,y:u*u*u*a.y+3*u*u*t*c.y1+3*u*t*t*c.y2+t*t*t*b.y}}
 function segment(a,b,rgb,t,seedVal){const c0=bez(a,b,seedVal);ctx.save();ctx.globalCompositeOperation='lighter';const pts=[];for(let k=18;k>=0;k--){const tt=Math.max(0,t-k*.0125);pts.push(cubic(a,c0,b,tt))}for(const [lw,al] of [[9,.025],[4,.075],[1.25,.46]]){ctx.beginPath();pts.forEach((p,i)=>i?ctx.lineTo(p.x,p.y):ctx.moveTo(p.x,p.y));ctx.strokeStyle=rgba(rgb,al*(.55+.45*Math.sin(Math.PI*t)));ctx.lineWidth=lw;ctx.lineCap='round';ctx.stroke()}for(let k=8;k>=0;k--){const tt=Math.max(0,t-k*.021),p=cubic(a,c0,b,tt),a0=(1-k/10)*(.92*(.55+.45*Math.sin(Math.PI*t)));glow(p.x,p.y,.40+k*.015,rgb,a0)}const head=cubic(a,c0,b,t);glow(head.x,head.y,.78,rgb,.98);if(t>.90){const q=(t-.90)/.10,r=5+q*36;ctx.beginPath();ctx.arc(b.x,b.y,r,0,TAU);ctx.strokeStyle=rgba(rgb,(1-q)*.28);ctx.lineWidth=.8;ctx.stroke()}ctx.restore()}
 function core(time){return project([0,0,0],time)}
 function draw(time){ctx.setTransform(dpr,0,0,dpr,0,0);ctx.clearRect(0,0,w,h);const elapsed=time-start,cp=core(elapsed),coreRgb=[255,158,31];
  const field=ctx.createRadialGradient(cp.x,cp.y,0,cp.x,cp.y,Math.min(w,h)*.40);field.addColorStop(0,'rgba(255,128,0,.075)');field.addColorStop(.32,'rgba(255,128,0,.026)');field.addColorStop(1,'rgba(255,128,0,0)');ctx.fillStyle=field;ctx.fillRect(0,0,w,h);
  ctx.save();ctx.globalCompositeOperation='lighter';for(const d of dust){const a=d.a+elapsed*.000025*(d.z>0?1:-1),v=[Math.cos(a)*d.r,d.y+Math.sin(a*.7+d.p)*25,Math.sin(a)*d.r+d.z],p=project(v,elapsed),depth=Math.max(.1,Math.min(1,(p.z+380)/760));glow(p.x,p.y,.08+.10*depth,[255,150,35],.018+.040*depth)}ctx.restore();
  ctx.save();ctx.globalCompositeOperation='lighter';for(let i=0;i<6;i++){ctx.save();ctx.translate(cp.x,cp.y);ctx.rotate(elapsed*(i%2?.00016:-.00013)+i*.61);ctx.scale(1,.24+i*.065);ctx.beginPath();ctx.arc(0,0,52+i*19,0,TAU);ctx.strokeStyle=`rgba(255,160,34,${.17-i*.020})`;ctx.lineWidth=.75;ctx.stroke();ctx.restore()}for(let i=0;i<28;i++){const a=i/28*TAU+elapsed*.00033*(i%2?1:-1),r=34+(i%7)*10;glow(cp.x+Math.cos(a)*r,cp.y+Math.sin(a)*r*.36,.17,i%4?[255,137,10]:[255,226,154],.48)}
  const cr=46,ang=elapsed*.00028,ca=Math.cos(ang),sa=Math.sin(ang),cb=Math.cos(ang*.63),sb=Math.sin(ang*.63),verts=[[cr,0,0],[-cr,0,0],[0,cr,0],[0,-cr,0],[0,0,cr],[0,0,-cr]].map(v=>{let x=ca*v[0]+sa*v[2],z=-sa*v[0]+ca*v[2],y=cb*v[1]-sb*z,z2=sb*v[1]+cb*z;return{x:cp.x+x,y:cp.y+y*.78,z:z2}}),edges=[[0,2],[0,3],[0,4],[0,5],[1,2],[1,3],[1,4],[1,5],[2,4],[4,3],[3,5],[5,2]];edges.forEach(([a,b])=>{const A=verts[a],B=verts[b],dep=Math.max(.2,Math.min(1,(A.z+B.z+92)/184));ctx.beginPath();ctx.moveTo(A.x,A.y);ctx.lineTo(B.x,B.y);ctx.strokeStyle=`rgba(255,203,112,${.10+.20*dep})`;ctx.lineWidth=.65+.6*dep;ctx.stroke()});verts.forEach(v=>glow(v.x,v.y,.26,[255,205,118],.34));glow(cp.x,cp.y,3.0,coreRgb,1);ctx.restore();
  ctx.save();ctx.globalCompositeOperation='lighter';Object.entries(role).forEach(([name,r],ri)=>{const p0=project(r.center,elapsed),rgb=r.rgb;for(let k=0;k<2;k++){ctx.save();ctx.translate(p0.x,p0.y);ctx.rotate(elapsed*(ri%2?.00005:-.000045)+ri*.7+k*.9);ctx.scale(1,.38+k*.14);ctx.beginPath();ctx.arc(0,0,42+k*18,0,TAU);ctx.strokeStyle=rgba(rgb,.030+k*.012);ctx.lineWidth=.55;ctx.stroke();ctx.restore()}});ctx.restore();
  const pos={};let all=[];Object.keys(nodes).forEach(name=>{pos[name]=nodes[name].map(n=>{const v=nodeWorld(n,elapsed),p=project(v,elapsed);const o={n,p};all.push({name,...o});return p})});all.sort((a,b)=>a.p.z-b.p.z);all.forEach(o=>{const depth=Math.max(.22,Math.min(1,(o.p.z+280)/560));drawNode(o.p,o.name,.28+.66*depth)});
  const cycle=7600,stageDur=cycle/4;events.forEach((e,ei)=>{let t=(elapsed+e.offset)%cycle,stage=Math.min(3,Math.floor(t/stageDur)),u=(t-stage*stageDur)/stageDur;u=u*u*(3-2*u);const src=pos[e.source][e.si],cmp=pos.compute[e.ci],prf=pos.proof[e.pi],outP=project([300,0,55+(ei%3-1)*45],elapsed);let a,b,rgb,bias=(ei%2?1:-1);if(stage===0){a=src;b=cp;rgb=role[e.source].rgb}else if(stage===1){a=cp;b=e.compute?cmp:prf;rgb=e.compute?role.compute.rgb:role.proof.rgb}else if(stage===2){a=e.compute?cmp:cp;b=prf;rgb=role.proof.rgb}else{a=prf;b=outP;rgb=[255,225,156]}segment(a,b,rgb,u,bias)});
  ctx.save();ctx.globalCompositeOperation='lighter';for(let i=0;i<2;i++){const q=reduce?.45:((elapsed*.000095+i*.52)%1),r=74+q*130;ctx.beginPath();ctx.arc(cp.x,cp.y,r,0,TAU);ctx.strokeStyle=`rgba(255,225,164,${.065*(1-q)})`;ctx.lineWidth=.7;ctx.stroke()}ctx.restore();
 }
 function loop(t){if(t-last>1000/FPS){last=t;draw(t)}if(!reduce&&visible&&!document.hidden)raf=requestAnimationFrame(loop);else raf=0}
 resize();draw(performance.now());if('ResizeObserver'in window)new ResizeObserver(()=>{resize();draw(performance.now())}).observe(c);if('IntersectionObserver'in window)new IntersectionObserver(e=>{visible=!!e[0]?.isIntersecting;if(visible&&!raf&&!reduce)raf=requestAnimationFrame(loop)},{rootMargin:'180px'}).observe(c);const host=c.closest('.hero');if(host&&matchMedia('(pointer:fine)').matches){host.addEventListener('pointermove',e=>{const r=host.getBoundingClientRect();mouseX=((e.clientX-r.left)/r.width-.5)*.8;mouseY=((e.clientY-r.top)/r.height-.5)*.45},{passive:true});host.addEventListener('pointerleave',()=>{mouseX*=.18;mouseY*=.18})}if(!reduce)raf=requestAnimationFrame(loop)
})();

// Accurate Earth — CPU texture-mapped sphere, browser-independent
(()=>{
 const canvas=document.getElementById('earthGL'),overlay=document.getElementById('earthNet'),ctx=canvas.getContext('2d',{alpha:true}),ox=overlay.getContext('2d');if(!ctx||!ox)return;let W=1,H=1,D=1,raf=0,last=0,visible=true,start=performance.now(),yaw=1.92,pitch=.17,targetYaw=yaw,targetPitch=pitch,srcData=null,srcW=0,srcH=0,mapCanvas=document.createElement('canvas'),mapCtx=mapCanvas.getContext('2d'),sphere=document.createElement('canvas'),sctx=sphere.getContext('2d'),S=420,geo=null;
 const hubs=[[25.76,-80.19],[40.71,-74.01],[37.77,-122.42],[51.51,-.13],[25.20,55.27],[1.35,103.82],[35.68,139.65],[-33.87,151.21],[-23.55,-46.63],[-26.20,28.05]],links=[[0,1],[0,2],[1,3],[3,4],[4,5],[5,6],[6,7],[0,8],[3,9],[9,4]],TAU=Math.PI*2;
 const light=(()=>{let v=[-.45,.65,1],m=Math.hypot(...v);return v.map(n=>n/m)})();
 const img=new Image();img.onload=()=>{mapCanvas.width=img.naturalWidth;mapCanvas.height=img.naturalHeight;mapCtx.drawImage(img,0,0);srcW=mapCanvas.width;srcH=mapCanvas.height;srcData=mapCtx.getImageData(0,0,srcW,srcH).data;prepareSphere();draw(performance.now())};img.src=EARTH_TEXTURE;
 function prepareSphere(){S=innerWidth<650?300:innerWidth<1100?380:480;sphere.width=sphere.height=S;const N=S*S;geo={nx:new Float32Array(N),ny:new Float32Array(N),nz:new Float32Array(N),inside:new Uint8Array(N),shade:new Float32Array(N),fres:new Float32Array(N)};const R=S*.475,c=S/2;for(let y=0;y<S;y++)for(let x=0;x<S;x++){const i=y*S+x,sx=(x+.5-c)/R,sy=(y+.5-c)/R,r2=sx*sx+sy*sy;if(r2>1)continue;const nx=sx,ny=-sy,nz=Math.sqrt(Math.max(0,1-r2));geo.inside[i]=1;geo.nx[i]=nx;geo.ny[i]=ny;geo.nz[i]=nz;geo.shade[i]=.34+.66*Math.max(0,nx*light[0]+ny*light[1]+nz*light[2]);geo.fres[i]=Math.pow(1-nz,2.15)}}
 function resize(){const r=canvas.getBoundingClientRect();D=Math.min(devicePixelRatio||1,2);W=Math.max(1,r.width);H=Math.max(1,r.height);canvas.width=overlay.width=Math.round(W*D);canvas.height=overlay.height=Math.round(H*D);ctx.setTransform(D,0,0,D,0,0);ox.setTransform(D,0,0,D,0,0);const desired=innerWidth<650?300:innerWidth<1100?380:480;if(desired!==S&&srcData)prepareSphere()}
 function sample(u,v){let x=((u%1+1)%1)*(srcW-1),y=Math.max(0,Math.min(1,v))*(srcH-1),ix=x|0,iy=y|0,j=(iy*srcW+ix)*4;return[srcData[j],srcData[j+1],srcData[j+2]]}
 function renderSphere(){if(!srcData||!geo)return;const out=sctx.createImageData(S,S),dst=out.data,cy=Math.cos(yaw),sy=Math.sin(yaw),cp=Math.cos(pitch),sp=Math.sin(pitch);for(let i=0;i<S*S;i++){if(!geo.inside[i])continue;let x=geo.nx[i],y=geo.ny[i],z=geo.nz[i];let y1=cp*y+sp*z,z1=-sp*y+cp*z;let xw=cy*x+sy*z1,zw=-sy*x+cy*z1,yw=y1;let lon=Math.atan2(zw,xw),lat=Math.asin(Math.max(-1,Math.min(1,yw))),u=lon/TAU+.5,v=.5-lat/Math.PI,rgb=sample(u,v),sh=geo.shade[i],coast=Math.max(0,Math.min(1,(rgb[0]-55)/150)),fr=geo.fres[i],j=i*4;dst[j]=Math.min(255,rgb[0]*sh*1.12+255*coast*.21+255*fr*.10);dst[j+1]=Math.min(255,rgb[1]*sh*1.08+108*coast*.18+110*fr*.085);dst[j+2]=Math.min(255,rgb[2]*sh*1.05+14*coast*.08+20*fr*.045);dst[j+3]=255}sctx.putImageData(out,0,0)}
 function v3(lat,lo){const p=lat*Math.PI/180,l=lo*Math.PI/180,c=Math.cos(p);return[c*Math.cos(l),Math.sin(p),c*Math.sin(l)]}function rot(v){let [xx,yy,zz]=v,cy=Math.cos(yaw),sy=Math.sin(yaw),x1=cy*xx-sy*zz,z1=sy*xx+cy*zz,cp=Math.cos(pitch),sp=Math.sin(pitch),y1=cp*yy-sp*z1,z2=sp*yy+cp*z1;return[x1,y1,z2]}function proj(v){const r=rot(v),R=Math.min(W,H)*.405;return{x:W*.5+r[0]*R,y:H*.5-r[1]*R,z:r[2]}}function slerp(a,b,t){let va=v3(a[0],a[1]),vb=v3(b[0],b[1]),dot=Math.max(-1,Math.min(1,va[0]*vb[0]+va[1]*vb[1]+va[2]*vb[2])),om=Math.acos(dot),so=Math.sin(om);if(so<1e-5)return va;let A=Math.sin((1-t)*om)/so,B=Math.sin(t*om)/so;return[va[0]*A+vb[0]*B,va[1]*A+vb[1]*B,va[2]*A+vb[2]*B]}
 function drawNetwork(t){ox.clearRect(0,0,W,H);ox.save();ox.globalCompositeOperation='lighter';links.forEach((L,i)=>{const a=hubs[L[0]],b=hubs[L[1]];ox.beginPath();let started=false;for(let k=0;k<=72;k++){const q=slerp(a,b,k/72),p=proj(q);if(p.z>0){started?ox.lineTo(p.x,p.y):ox.moveTo(p.x,p.y);started=true}else started=false}ox.strokeStyle='rgba(255,168,44,.18)';ox.lineWidth=.8;ox.stroke();const tt=reduce?.45:((t-start)*.000042+i*.119)%1,q=slerp(a,b,tt),p=proj(q);if(p.z>0){ox.beginPath();ox.arc(p.x,p.y,2.15,0,TAU);ox.fillStyle='rgba(255,196,108,.98)';ox.shadowColor='#ff8a00';ox.shadowBlur=13;ox.fill();ox.shadowBlur=0}});hubs.forEach(h=>{const p=proj(v3(h[0],h[1]));if(p.z>0){ox.beginPath();ox.arc(p.x,p.y,2.05,0,TAU);ox.fillStyle='rgba(255,144,12,.94)';ox.shadowColor='#ff8a00';ox.shadowBlur=11;ox.fill();ox.shadowBlur=0}});ox.restore()}
 function draw(t){yaw+=((targetYaw-yaw)*.035)+(reduce?0:.00038);pitch+=(targetPitch-pitch)*.035;renderSphere();ctx.clearRect(0,0,W,H);const R=Math.min(W,H)*.405,cx=W*.5,cy=H*.5,g=ctx.createRadialGradient(cx,cy,R*.74,cx,cy,R*1.18);g.addColorStop(0,'rgba(255,125,0,0)');g.addColorStop(.73,'rgba(255,125,0,.035)');g.addColorStop(1,'rgba(255,125,0,0)');ctx.fillStyle=g;ctx.fillRect(0,0,W,H);ctx.save();ctx.shadowColor='rgba(255,138,0,.22)';ctx.shadowBlur=32;ctx.globalAlpha=.97;ctx.drawImage(sphere,cx-R,cy-R,R*2,R*2);ctx.restore();ctx.beginPath();ctx.arc(cx,cy,R,0,TAU);ctx.strokeStyle='rgba(255,164,44,.21)';ctx.lineWidth=.8;ctx.stroke();drawNetwork(t)}
 function loop(t){if(t-last>(innerWidth<650?60:45)){last=t;draw(t)}if(!reduce&&visible&&!document.hidden)raf=requestAnimationFrame(loop);else raf=0}resize();new ResizeObserver(resize).observe(canvas);new IntersectionObserver(e=>{visible=!!e[0]?.isIntersecting;if(visible&&!raf&&!reduce)raf=requestAnimationFrame(loop)},{rootMargin:'180px'}).observe(canvas);const wrap=canvas.parentElement;if(matchMedia('(pointer:fine)').matches)wrap.addEventListener('pointermove',e=>{const r=wrap.getBoundingClientRect();targetYaw=1.92+((e.clientX-r.left)/r.width-.5)*.34;targetPitch=.17+((e.clientY-r.top)/r.height-.5)*-.20},{passive:true});if(!reduce)raf=requestAnimationFrame(loop)
})();
